############### German navigation ################

# Simple homepage link
[[main]]
weight = 10
name = "Startseite"
url = "/"

[[main]]
name = "Aktuelles"
url = "member/"
weight = 15

[[main]]
name = "Über uns"
url = "about/"
weight = 20

[[main]]
parent = "Über uns"
name = "Das Projekt"
url = "about/project"
weight = 10

[[main]]
parent = "Über uns"
name = "Die Menschen"
url = "people/"
weight = 20

[[main]]
parent = "Über uns"
name = "Wie wir leben"
url = "about/dailylife"
weight = 30

[[main]]
parent = "Über uns"
name = "In der Presse"
url = "about/dailylife"
weight = 40

[[main]]
parent = "Über uns"
name = "Galerie"
url = "about/photos"
weight = 50

[[main]]
name = "Mitwohnen"
url = "member/"
weight = 30

[[main]]
name = "Unterstützen"
url = "helping/"
weight = 32

[[main]]
name = "Kontakt"
url = "contact/"
weight = 35

# footer menu
[[footer]]
name = "Über uns"
url = "about/"
weight = 1

[[footer]]
name = "Kontakt"
url = "contact/"
weight = 2

[[footer]]
name = "Datenschutz"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "AGB"
url = "terms-conditions/"
weight = 4
