############### German navigation ################

# Simple homepage link

[[main]]
name = "Aktuelles"
url = "#"
weight = 40

[[main]]
parent = "Aktuelles"
name = "Veranstaltungskalender"
url = "kalender/"
weight = 10

[[main]]
parent = "Aktuelles"
name = "Neues vom staTThus"
url = "post/"
weight = 20


[[main]]
name = "Über uns"
url = "about/"
weight = 10

[[main]]
parent = "Über uns"
name = "Das Projekt"
url = "projekt/"
weight = 10

[[main]]
parent = "Über uns"
name = "Die Menschen"
url = "people/"
weight = 20

[[main]]
parent = "Über uns"
name = "Wie wir leben"
url = "themen/wie-wir-leben/"
weight = 30

[[main]]
name = "Wir im Quartier"
url = "themen/wir-im-quartier/"
weight = 30


[[main]]
name = "Mitwohnen"
url = "member/"
weight = 20

[[main]]
name = "Unterstützen"
url = "help/"
weight = 50

[[main]]
name = "Galerie"
url = "gallery/"
weight = 60

# footer menu
[[footer]]
name = "Newsletter"
url = "newsletter/"
weight = 2

[[footer]]
name = "Kontakt"
url = "kontakt/"
weight = 1

[[footer]]
name = "Datenschutz"
url = "datenschutz/"
weight = 4

[[footer]]
name = "Impressum"
url = "impressum/"
weight = 3
